### ISSUE TITLE
Getting a malformed buffer

### ISSUE THREAD

**Issue by davidgatti** [myshenin/aws-lambda-multipart-parser#12]
I'm running in this situation where the buffer that I get back from this module, is not correct. For example images won't be displayed because of this. It seams to me that your code is parsing the binary data from the request incorrectly.

**Comment by myshenin** [comment]
@davidgatti show an example

**Comment by Tutch** [comment]
I'd also like to know about this. I'm trying to save an .webm file and while the resulting file is correct, the video does not open. Maybe it's the file writing in itself that's not right? Here's my code:

`module.exports.handler = (event, context, callback) => {
    let data = multipart.parse(event, false);

    fs.writeFile('meme.webm', data.file.content, 'binary', function(err) {
        if(err) { 
          console.log(err);
        } else {  
          console.log('saved!');
        }
    }); 

    // etc ...
};`

**Comment by sparent** [comment]
+1 running into the same issue, incorrect buffer causing corrupted file

**Comment by Tutch** [comment]
Seems to be a problem on serverless offline's end.. Refer to [this issue](https://github.com/dherault/serverless-offline/issues/230#event-1570768893).

**Comment by myshenin** [comment]
@Tutch @sparent 
what are changes helped you?

**Comment by Tutch** [comment]
@myshenin the solution in [this issue right here](https://github.com/dherault/serverless-offline/issues/230#event-1570768893) solved the problem. But there's no need to worry anymore, because serverless-offline accepted the solution on this merge request [here](https://github.com/dherault/serverless-offline/pull/394). The current version of serverless-offline works as expected with this multiparser.

**Comment by myshenin** [comment]
@Tutch as I understood the issue is in encoding?
I tried to fix it with toString('binary') but it didn't work

**Comment by myshenin** [comment]
Unfortunately, there is an issue with malformed media files uploaded to S3. Let me explain on example, I send an image, which is 50Kb. I get a buffer, which is 50Kb. That fact indicates buffer is formed well, but some encoding issue happens with s3.upload and s3.putObject functions. If you have a solution or a hint, contact me myshenin.contact@gmail.com.
@Tutch 
@sparent 
@davidgatti

**Comment by djgovani** [comment]
@myshenin You can refer [my repo ](https://github.com/djgovani/Serverless-S3-FileUpload). Hope it'll help you

**Comment by Wolfie010** [comment]
@djgovani I tried your implementation for pdf files and it didn't help. Does anyone have another idea?
